services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data


  fastapi:
    build:
      context: .
    container_name: fastapi_app
    restart: always
    depends_on:
      - postgres
    ports:
      - "49152:8000"
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    volumes:
      - .:/app

    command: >
      sh -c "
        python -m app.sqlInstructions &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      "

volumes:
  pg_data:
