services:
  fastapi:
    build:
      context: .
    extra_hosts:
      - "yarnpkg.com:34.141.48.9"
    container_name: fastapi_app
    restart: always
    ports:
      - "49152:8000"
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    command: >
      sh -c "
        python -m app.sqlInstructions &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000
      "

  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: